### ISSUE TITLE
TestDouble.js - Should different semantics have different syntax?

### ISSUE THREAD

**Issue by deanius** [testdouble/feedback#20]
From the examples, 
```
save(41, 'Jill');

td.verify(save(41, 'Jill'));
```

When I try to figure out "What does calling a td.function (_save_) do?", I'm confused by its 2 ways of invoking it:
   - to register an invocation, as in your SUT
   - to define an argument to `verify`, ie create a 'verifiable' 

I am trying to understand without source, and strictly from a perspective that 'the tests I write should at least make sense to me', why the actual invocation looks identical to the definition of what should have happened. If they're the same function calls, what differentiates them? With eager evaluation, it seems that the act of creating the argument to `td.verify` might itself count as an invocation.

My suggestion (to throw something out there):

```
td.verify(() => save(41, 'Jill'))
```

An addition of syntax, yet it makes it clear to me that the existing list of invocations of the td.function will NOT be changed by the creation of an argument to verify, since wrapping it in a thunk can ensure that your list of invocations is 'frozen' at the time of calling verify.

I hope my confusion is clear, and that you can explain something that I've missed that makes it all ok :)

D

**Comment by deanius** [comment]
I suspect that this design is one reason this bug emerged: https://github.com/testdouble/testdouble.js/issues/117

I wonder if thinking about the API some more could reveal some similar cases that could be nipped early?

**Comment by searls** [comment]
I appreciate your feedback. 

So here's

1. `td.verify` and `td.when` should be perfectly symmetrical APIs. If you know one, you know the other.
2. The "rehearsal" or "demonstration" invocation to be identical between the subject & source so it can be easily copy-pasted from test to source and a grep for one will find the other (this is something no other test double library has been able to fully pull off, with Mockito being closest for its `when` stubbing)
3. To be configurable in obviously synchronous scripts. As soon as you pass a function, especially in recent years, any JavaScript developer should expect it to be scheduled to execute on a later stack (which would then lead anyone using `td` to want a callback or a promise API for it). I'm pretty committed to synchronous tests being much preferable to async ones when possible, and would never want the library to be the first thing to encourage someone to flip a test from synchronous to not.

As for your suggestion, the implementation would be identical but with an additional call. The user is left to assume the test double library is going to invoke that function, then record all td invocations inside it (which is the same sort of "magic" that they experience now). However, in addition to the added syntax, it would open the door to users thinking they could wind up numerous test double invocations for a single stubbing or verification because functions invite multiple statements, which isn't at all how the API is designed and would yield surprising results. Especially with stubbing.

As for #117, it was a pretty simple fix and I don't think the suggested API change would have avoided it, since the stack push/popping algorithm would still have been how I'd have implemented it anyway.

**Comment by deanius** [comment]
Thanks for your reply Justin. The implication of async is one I hadn't considered.

Would you not run into trouble if the argument to verify were not created sufficiently close to when the verify occurred?

**Comment by searls** [comment]
I don't think I understand what you're asking. In the current implementation or in your proposed?
